esphome:
  name: st7796-lgfx-test

  libraries:
    - LovyanGFX=https://github.com/lovyan03/LovyanGFX.git

external_components:
  - source:
      type: git
      url: https://github.com/YiFan1010/esphome-lovyangfx
      ref: main
    components:
      - lovyangfx

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

display:
  - platform: lovyangfx
    id: lcd

    width: 320
    height: 480

    frequency: 10MHz

    pin_cs: 39
    pin_dc: 38
    pin_wr: 45

    pin_d0: 13
    pin_d1: 12
    pin_d2: 11
    pin_d3: 10
    pin_d4: 9
    pin_d5: 46
    pin_d6: 3
    pin_d7: 8

    pin_d8: 18
    pin_d9: 17
    pin_d10: 16
    pin_d11: 15
    pin_d12: 7
    pin_d13: 6
    pin_d14: 5
    pin_d15: 4

    rotation: 0
    invert: true
    rgb_order: false

    update_interval: 1s

    lambda: |-
      it.fill(Color::BLACK);

      it.filled_rectangle(
        0, 0, 320, 80,
        Color(255, 0, 0)
      );

      it.filled_rectangle(
        0, 80, 320, 160,
        Color(0, 255, 0)
      );

      it.filled_rectangle(
        0, 160, 320, 240,
        Color(0, 0, 255)
      );

      it.filled_rectangle(
        0, 240, 320, 320,
        Color(255, 255, 0)
      );

      it.filled_rectangle(
        0, 320, 320, 400,
        Color(255, 0, 255)
      );

      it.filled_rectangle(
        0, 400, 320, 480,
        Color(0, 255, 255)
      );
